"""empty message

Revision ID: 14f69929cfb7
Revises: 5063307e27af
Create Date: 2025-08-06 14:27:37.031835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f69929cfb7'
down_revision = '5063307e27af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_text', sa.String(length=500), nullable=False))
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.drop_column('comment_text')

    # ### end Alembic commands ###
